# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.1
loader_version=0.16.10
loom_version=1.9-SNAPSHOT

# Mod Properties
mod_version=3.0.1
maven_group=net.yigitguven.daylength
archives_base_name=day-length

# Dependencies
fabric_api_version=0.116.9+1.21.1
cloth_config_version=15.0.140
modmenu_version=11.0.3

# Toolchain
org.gradle.java.installations.auto-download=true
org.gradle.java.installations.auto-detect=true
org.gradle.java.home=C:/Users/User/.gradle/jdks/eclipse_adoptium-21-amd64-windows.2